//keymap_ansi.c
#include "keymap_ansi.h"

const keycode_ansi_escape_dict_entry keycode_ansi_escape_dictionary[] = {
    {KC_A, "a", "A"},
    {KC_B, "b", "B"},
    {KC_C, "c", "C"},
    {KC_D, "d", "D"},
    {KC_E, "e", "E"},
    {KC_F, "f", "F"},
    {KC_G, "g", "G"},
    {KC_H, "h", "H"},
    {KC_I, "i", "I"},
    {KC_J, "j", "J"},
    {KC_K, "k", "K"},
    {KC_L, "l", "L"},
    {KC_M, "m", "M"},
    {KC_N, "n", "N"},
    {KC_O, "o", "O"},
    {KC_P, "p", "P"},
    {KC_Q, "q", "Q"},
    {KC_R, "r", "R"},
    {KC_S, "s", "S"},
    {KC_T, "t", "T"},
    {KC_U, "u", "U"},
    {KC_V, "v", "V"},
    {KC_W, "w", "W"},
    {KC_X, "x", "X"},
    {KC_Y, "y", "Y"},
    {KC_Z, "z", "Z"},
    {KC_1, "1", "1"},
    {KC_2, "2", "2"},
    {KC_3, "3", "3"},
    {KC_4, "4", "4"},
    {KC_5, "5", "5"},
    {KC_6, "6", "6"},
    {KC_7, "7", "7"},
    {KC_8, "8", "8"},
    {KC_9, "9", "9"},
    {KC_0, "0", "0"},
    {KC_MINUS, "-", "_"},
    {KC_EQUAL, "=", "+"},
    {KC_LBRC, "[", "{"},
    {KC_RBRC, "]", "}"},
    {KC_BSLS, "\\", "|"},
    {KC_SCLN, ";", ";"},
    {KC_QUOTE, "'", "\""},
    {KC_GRAVE, "`", "`"},
    {KC_COMMA, ",", "<"},
    {KC_DOT, ".", ">"},
    {KC_SLASH, "/", "?"},
    {KC_SPACE, " ", " "},
    {KC_EXCLAIM, "!", "!"},
    {KC_AT, "@", "@"},
    {KC_HASH, "#", "#"},
    {KC_DOLLAR, "$", "$"},
    {KC_PERCENT, "%", "%"},
    {KC_CIRCUMFLEX, "^", "^"},
    {KC_AMPERSAND, "&", "&"},
    {KC_ASTERISK, "*", "*"},
    {KC_LPRN, "(", "("},
    {KC_RPRN, ")", ")"},
    {KC_UNDERSCORE, "_", "_"},
    {KC_PLUS, "+", "+"},
    {KC_LCBR, "{", "{"},
    {KC_RCBR, "}", "}"},
    {KC_PIPE, "|", "|"},
    {KC_TILDE, "`", "`"},
    {KC_BACKSPACE, "\x08", "\x1B[1;6K"},
    {KC_ESC, "\x1B", "\x1B[1;6L"},
    {KC_TAB, "\x09", "\x1B[1;6M"},
    {KC_ENTER, "\x0D", "\x1B[1;6N"},
    {KC_SPACE, " ", "\x1B[1;6O"},
    {KC_DELETE, "\x1B[3~", "\x1B[1;6P"},
    {KC_UP, "\x1B[A", "\x1B[1;6Q"},
    {KC_DOWN, "\x1B[B", "\x1B[1;6R"},
    {KC_RIGHT, "\x1B[C", "\x1B[1;6S"},
    {KC_LEFT, "\x1B[D", "\x1B[1;6T"},
    {KC_INSERT, "\x1B[2~", "\x1B[1;6U"},
    {KC_HOME, "\x1B[H", "\x1B[1;6V"},
    {KC_END, "\x1B[F", "\x1B[1;6W"},
    {KC_PAGE_UP, "\x1B[5~", "\x1B[1;6X"},
    {KC_PAGE_DOWN, "\x1B[6~", "\x1B[1;6Y"},
    {KC_NUM, "\x1BOP", "\x1BOP"},
    {KC_KP_SLASH, "/", "?"},
    {KC_KP_ASTERISK, "*", "*"},
    {KC_KP_MINUS, "-", "_"},
    {KC_KP_PLUS, "+", "+"},
    {KC_KP_ENTER, "\x0D", "\x0D"},
    {KC_KP_1, "1", "!"},
    {KC_KP_2, "2", "@"},
    {KC_KP_3, "3", "#"},
    {KC_KP_4, "4", "$"},
    {KC_KP_5, "5", "%"},
    {KC_KP_6, "6", "^"},
    {KC_KP_7, "7", "&"},
    {KC_KP_8, "8", "*"},
    {KC_KP_9, "9", "("},
    {KC_KP_0, "0", ")"},
    {KC_KP_DOT, ".", "!"},
    {KC_LCTL, "\x1B[1;5A", "\x1B[1;6A"},
    {KC_LSFT, "\x1B[1;2D", "\x1B[1;6D"},
    {KC_LALT, "\x1B[1;3D", "\x1B[1;6E"},
    {KC_LGUI, "\x1B[1;4D", "\x1B[1;6F"},
    {KC_RCTL, "\x1B[1;5C", "\x1B[1;6G"},
    {KC_RSFT, "\x1B[1;2C", "\x1B[1;6H"},
    {KC_RALT, "\x1B[1;3C", "\x1B[1;6I"},
    {KC_RGUI, "\x1B[1;4C", "\x1B[1;6J"},
};

const ansi_escape_keycode_entry ansi_escape_keycode_dictionary[] = {
    {"a", KC_A, false},
    {"b", KC_B, false},
    {"c", KC_C, false},
    {"d", KC_D, false},
    {"e", KC_E, false},
    {"f", KC_F, false},
    {"g", KC_G, false},
    {"h", KC_H, false},
    {"i", KC_I, false},
    {"j", KC_J, false},
    {"k", KC_K, false},
    {"l", KC_L, false},
    {"m", KC_M, false},
    {"n", KC_N, false},
    {"o", KC_O, false},
    {"p", KC_P, false},
    {"q", KC_Q, false},
    {"r", KC_R, false},
    {"s", KC_S, false},
    {"t", KC_T, false},
    {"u", KC_U, false},
    {"v", KC_V, false},
    {"w", KC_W, false},
    {"x", KC_X, false},
    {"y", KC_Y, false},
    {"z", KC_Z, false},
    {"A", KC_A, true},
    {"B", KC_B, true},
    {"C", KC_C, true},
    {"D", KC_D, true},
    {"E", KC_E, true},
    {"F", KC_F, true},
    {"G", KC_G, true},
    {"H", KC_H, true},
    {"I", KC_I, true},
    {"J", KC_J, true},
    {"K", KC_K, true},
    {"L", KC_L, true},
    {"M", KC_M, true},
    {"N", KC_N, true},
    {"O", KC_O, true},
    {"P", KC_P, true},
    {"Q", KC_Q, true},
    {"R", KC_R, true},
    {"S", KC_S, true},
    {"T", KC_T, true},
    {"U", KC_U, true},
    {"V", KC_V, true},
    {"W", KC_W, true},
    {"X", KC_X, true},
    {"Y", KC_Y, true},
    {"Z", KC_Z, true},
    {"1", KC_1, false},
    {"2", KC_2, false},
    {"3", KC_3, false},
    {"4", KC_4, false},
    {"5", KC_5, false},
    {"6", KC_6, false},
    {"7", KC_7, false},
    {"8", KC_8, false},
    {"9", KC_9, false},
    {"0", KC_0, false},
    {" ", KC_SPACE, false},
    {"-", KC_MINUS, false},
    {"_", KC_UNDS, false},
    {"=", KC_EQUAL, false},
    {"[", KC_LBRC, false},
    {"]", KC_RBRC, false},
    {"\\", KC_BSLS, false},
    {";", KC_SCLN, false},
    {":", KC_COLN, true},
    {"'", KC_QUOTE, false},
    {"`", KC_GRAVE, false},
    {",", KC_COMMA, false},
    {".", KC_DOT, false},
    {"/", KC_SLASH, false},
    {" ", KC_SPACE, false},
    {"!", KC_EXCLAIM, true},
    {"@", KC_AT, true},
    {"#", KC_HASH, true},
    {"$", KC_DOLLAR, true},
    {"%", KC_PERCENT, true},
    {"^", KC_CIRCUMFLEX, true},
    {"&", KC_AMPERSAND, true},
    {"*", KC_ASTERISK, true},
    {"(", KC_LPRN, true},
    {")", KC_RPRN, true},
    {"_", KC_UNDERSCORE, true},
    {"+", KC_PLUS, true},
    {"{", KC_LBRC, true},
    {"}", KC_RBRC, true},
    {"|", KC_PIPE, true},
    {"`", KC_TILDE, true},
    {"\x08", KC_BACKSPACE, false},
    {"\x1B", KC_ESC, false},
    {"\x09", KC_TAB, false},
    {"\x0D", KC_ENTER, false},
    {"\x1B[3~", KC_DELETE, false},
    {"\x1B[A", KC_UP, false},
    {"\x1B[B", KC_DOWN, false},
    {"\x1B[C", KC_RIGHT, false},
    {"\x1B[D", KC_LEFT, false},
    {"\x1B[2~", KC_INSERT, false},
    {"\x1B[H", KC_HOME, false},
    {"\x1B[F", KC_END, false},
    {"\x1B[5~", KC_PAGE_UP, false},
    {"\x1B[6~", KC_PAGE_DOWN, false},
    {"\x1BOP", KC_NUM, false},
    {"/", KC_KP_SLASH, true},
    {"*", KC_KP_ASTERISK, true},
    {"-", KC_KP_MINUS, true},
    {"+", KC_KP_PLUS, true},
    {"\x1B[1;5A", KC_LCTL, false},
    {"\x1B[1;2D", KC_LSFT, false},
    {"\x1B[1;3D", KC_LALT, false},
    {"\x1B[1;4D", KC_LGUI, false},
    {"\x1B[1;5C", KC_RCTL, false},
    {"\x1B[1;2C", KC_RSFT, false},
    {"\x1B[1;3C", KC_RALT, false},
    {"\x1B[1;4C", KC_RGUI, false},
};
uint8_t NUM_ANSI_ESCAPE_KEYCODE = sizeof(ansi_escape_keycode_dictionary) / sizeof(ansi_escape_keycode_entry);
uint8_t NUM_KEYCODE_ANSI_ESCAPE = sizeof(keycode_ansi_escape_dictionary) / sizeof(keycode_ansi_escape_dict_entry);

const char *keycode_to_escape_sequence(uint16_t keycode, int shift) {
    for (uint8_t i = 0; i < NUM_KEYCODE_ANSI_ESCAPE; ++i) {
        if (keycode_ansi_escape_dictionary[i].keycode == keycode) {
            return shift ? keycode_ansi_escape_dictionary[i].ansi_escape_shifted : keycode_ansi_escape_dictionary[i].ansi_escape;
        }
    }
    return NULL;
}

uint16_t escape_sequence_to_keycode(const char *escape_sequence, bool *shift_needed) {
    for (uint8_t i = 0; i < NUM_ANSI_ESCAPE_KEYCODE; ++i) {
        if (strcmp(ansi_escape_keycode_dictionary[i].ansi_escape, escape_sequence) == 0) {
            *shift_needed = ansi_escape_keycode_dictionary[i].shifted;
            return ansi_escape_keycode_dictionary[i].keycode;
        }
    }
    return 0;
}
